from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('run/', views.run_form, name='run_form'),
    path('run/submit/', views.run_submit, name='run_submit'),
    path('simulations/', views.simulations_list, name='simulations_list'),
    path('simulations/<int:sim_id>/', views.simulation_detail, name='simulation_detail'),
    path('simulations/<int:sim_id>/progress/', views.simulation_progress, name='simulation_progress'),
    path('simulations/<int:sim_id>/delete/', views.simulation_delete, name='simulation_delete'),
    path('game/<int:game_id>/replay/', views.game_replay, name='game_replay'),
    path('game/<int:game_id>/delete/', views.game_delete, name='game_delete'),
    path('play/', views.play_menu, name='play_menu'),
    path('play/bot/', views.play_bot_form, name='play_bot_form'),
    path('play/bot/new/', views.play_bot_create, name='play_bot_create'),
    path('play/human/', views.play_human_lobby, name='play_human_lobby'),
    path('play/pvp/create/', views.play_pvp_create, name='play_pvp_create'),
    path('play/pvp/join/', views.play_pvp_join_lobby, name='play_pvp_join_lobby'),
    path('play/pvp/join/code/', views.play_pvp_join_by_code, name='play_pvp_join_by_code'),
    path('play/pvp/join/<int:game_id>/', views.play_pvp_join_form, name='play_pvp_join_form_id'),
    path('play/pvp/join/<int:game_id>/submit/', views.play_pvp_join, name='play_pvp_join'),
    path('play/games/', views.play_games_list, name='play_games_list'),
    path('play/game/<int:game_id>/', views.play_game_page, name='play_game_page'),
    path('play/game/<int:game_id>/move/', views.play_game_move, name='play_game_move'),
    path('play/game/<int:game_id>/forfeit/', views.play_game_forfeit, name='play_game_forfeit'),
    path('play/game/<int:game_id>/state/', views.play_game_state, name='play_game_state'),
    path('play/game/<int:game_id>/replay/', views.player_game_replay, name='player_game_replay'),
    path('bots/', views.bots_docs, name='bots_docs'),
    path('ia/', views.math_ia, name='math_ia'),
    path('scenario/', views.scenario_builder, name='scenario_builder'),
    path('scenario/run/', views.scenario_run, name='scenario_run'),
]
