# Generated by Django 5.2.14 on 2026-06-20 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_index', models.IntegerField()),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('winner', models.IntegerField(default=-1)),
                ('rounds', models.IntegerField(default=0)),
                ('total_turns', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['game_index'],
            },
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot1_name', models.CharField(max_length=50)),
                ('bot2_name', models.CharField(max_length=50)),
                ('num_games', models.IntegerField(default=100)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('games_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('player', models.IntegerField()),
                ('action_type', models.CharField(blank=True, max_length=20)),
                ('source_idx', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('line_idx', models.IntegerField(default=0)),
                ('score_p1_before', models.IntegerField(default=0)),
                ('score_p2_before', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='azul.game')),
            ],
            options={
                'ordering': ['turn'],
            },
        ),
        migrations.CreateModel(
            name='PlayerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.CharField(max_length=100)),
                ('player2_name', models.CharField(blank=True, max_length=100)),
                ('bot1_name', models.CharField(blank=True, max_length=50)),
                ('bot2_name', models.CharField(blank=True, max_length=50)),
                ('mode', models.CharField(choices=[('pve', 'vs Bot'), ('pvp', 'vs Human')], default='pve', max_length=10)),
                ('seed', models.IntegerField(blank=True, null=True)),
                ('score1', models.IntegerField(default=0)),
                ('score2', models.IntegerField(default=0)),
                ('winner', models.IntegerField(default=-1)),
                ('rounds', models.IntegerField(default=0)),
                ('total_turns', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_games_as_p1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_games_as_p2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('player', models.IntegerField()),
                ('action_type', models.CharField(blank=True, max_length=20)),
                ('source_idx', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('line_idx', models.IntegerField(default=0)),
                ('score_p1_before', models.IntegerField(default=0)),
                ('score_p2_before', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='azul.playergame')),
            ],
            options={
                'ordering': ['turn'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('state_json', models.TextField()),
                ('action_desc', models.TextField(blank=True)),
                ('evaluations_json', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='azul.playergame')),
            ],
            options={
                'ordering': ['turn'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='azul_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='azul.simulation'),
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn', models.IntegerField()),
                ('state_json', models.TextField()),
                ('action_desc', models.TextField(blank=True)),
                ('evaluations_json', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='azul.game')),
            ],
            options={
                'ordering': ['turn'],
            },
        ),
    ]
