# Generated by Django 5.2.14 on 2026-06-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='colors1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='colors2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='cols1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='cols2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='floor_penalty_p1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='floor_penalty_p2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='rows1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='rows2',
            field=models.IntegerField(default=0),
        ),
    ]
