# Generated by Django 5.2.14 on 2026-06-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azul', '0002_game_colors1_game_colors2_game_cols1_game_cols2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='hundred_point_rule',
            field=models.BooleanField(default=False),
        ),
    ]
